// ============================================================
// [Test] Handshake SVA — Simulator
// Sample showing expansion of snippet: sva-sim-handshake
// Used as a place to paste SVA generated by Copilot Chat
// ============================================================

// ---- Paste snippets or Copilot-generated SVA here for testing ----

// --- Snippet Test: sva-sim-handshake ---
// Type "sva-sim-handshake" in a .sv file → press Tab to verify expansion

// --- Copilot Chat Test ---
// Copy and paste the following into Copilot Chat (Cmd+Shift+I) to try:
//
//   [Simulator]
//   Generate SVA to verify a valid/ready handshake.
//   Signal names: valid, ready, data (32-bit)
//   Clock: clk, reset: rst_n (active-low)

// ============================================================
// Expected generated output (for reference)
// ============================================================

// Hold valid high until ready arrives while valid is high
property prop_valid_stable;
  @(posedge clk) disable iff (!rst_n)
  (valid && !ready) |=> valid;
endproperty

property prop_data_stable;
  @(posedge clk) disable iff (!rst_n)
  (valid && !ready) |=> $stable(data);
endproperty

AST_VALID_STABLE: assert property (prop_valid_stable)
  else $error("[ASSERT FAIL] VALID_STABLE: valid dropped before ready at %t", $time);
AST_DATA_STABLE:  assert property (prop_data_stable)
  else $error("[ASSERT FAIL] DATA_STABLE: data changed while valid at %t", $time);

COV_HANDSHAKE:    cover property (@(posedge clk) valid && ready);
COV_VALID_WAIT:   cover property (@(posedge clk) valid && !ready);
